### ISSUE TITLE
No syntax highlight on code blocks

### ISSUE THREAD

**Issue by ulfben** [OleVik/grav-plugin-presentation-deckset#3]
Sorry for spamming you like this, and thank you so much for the excellent work you've put into the presentation plugin!

So, [deckset claims to support syntax highlighting](https://docs.deckset.com/English.lproj/Formatting/06-code-blocks.html) using "GitHub style fenced code blocks to specify the language".  But I am entirely unable to replicate their example with this plugin. 

I have tried: 
- installing the Highlight v1.4.0 plugin
- running with and without DecksetParser
- and I've tried adding
```
highlight:
    enabled: true
    lines: true
```
to the front matter of the page. 

I'm copy pasting their exact example and the code comes out wrapped neatly in `<code class="language-javascript">` but no highlighting happens. What am I doing wrong?

![no_syntax_highlight](https://user-images.githubusercontent.com/5237741/56086044-ad550100-5e4e-11e9-90bf-9f581d2a361b.png)

**Comment by ulfben** [comment]
I should add that there are no warnings or loading errors in the Chrome Developer Console. In fact, looking at the source code of the page I can't see anything that immediately seem to be related to highlight.js... 

But the highlight plugin is running so ... I have no idea. :P

**Comment by OleVik** [comment]
No problem at all, your issues are succinct and make it easy to iron out the kinks.

This one is quite easy to identify: Highlight, and plugins generally, push assets into Grav's asset manager without any restrictions. The Presentation plugin does not, to avoid unnecessary requests and conflicts, load all assets at once. So [Highlight's assets](https://github.com/getgrav/grav-plugin-highlight/blob/1.4.0/highlight.php#L54-L60) are [not loaded by the plugin](https://github.com/OleVik/grav-plugin-presentation/blob/v1.6.4/templates/presentation.html.twig).

The fix is to, in your child-theme or extension otherwise, push these assets to one of the groups used by Presentation. In the .php-file, in the `getSubscribedEvents`-method, make sure you are listening for the `onTwigSiteVariables`-event like [Quark Open Publishing does](https://github.com/hibbitts-design/grav-theme-quark-open-publishing/blob/v1.6.1/quark-open-publishing.php#L21). Add a `onTwigSiteVariables`-method like [it does](https://github.com/hibbitts-design/grav-theme-quark-open-publishing/blob/v1.6.1/quark-open-publishing.php#L64-L70), but within it add this:

```php
$init = "hljs.initHighlightingOnLoad();\n";
if ($this->config->get('plugins.highlight.lines')) {
    $init .= "hljs.initLineNumbersOnLoad();\n";
}
$theme = $this->config->get('plugins.highlight.theme') ?: 'default';
$this->grav['assets']->addCss('plugin://highlight/css/'.$theme.'.css', null, 'bottom');
$this->grav['assets']->addJs('plugin://highlight/js/highlight.pack.js', null, 'bottom');
if ($this->config->get('plugins.highlight.lines')) {
    $this->grav['assets']->addJs('plugin://highlight/js/highlightjs-line-numbers.min.js', null, 'bottom');
    $this->grav['assets']->addCss('plugin://highlight/css/highlightjs-line-numbers.css', null, 'bottom');
}
$this->grav['assets']->addInlineJs($init, null, 'bottom');
```

This adds these assets to one of the groups that [Presentation uses](https://github.com/OleVik/grav-plugin-presentation/blob/v1.6.4/templates/presentation.html.twig#L166).

I'll admit this is not the easiest way to do this, but I've yet to find a system to do it that causes less conflicts when very few plugins register assets in a uniform way. A template-extension may be apt, or perhaps just an option to load every asset like normal.

**Comment by ulfben** [comment]
Ouch - creating a child theme is more involvement than I was hoping to have with Grav. :D 

As a quick-and-dirty hack to I tried adding the subscription in your plugin file instead (`/user/plugins/presentation/presentation.php`):

```
 public static function getSubscribedEvents()
    {
        return [
            'onPluginsInitialized' => ['onPluginsInitialized', 0],
			'onTwigSiteVariables' => ['onTwigSiteVariables', 0]
        ];
    }
```

```
public function onTwigSiteVariables()
{
   $init = "hljs.initHighlightingOnLoad();\n";
	if ($this->config->get('plugins.highlight.lines')) {
		$init .= "hljs.initLineNumbersOnLoad();\n";
	}
	$theme = $this->config->get('plugins.highlight.theme') ?: 'default';
	$this->grav['assets']->addCss('plugin://highlight/css/'.$theme.'.css', null, 'bottom');
	$this->grav['assets']->addJs('plugin://highlight/js/highlight.pack.js', null, 'bottom');
	if ($this->config->get('plugins.highlight.lines')) {
		$this->grav['assets']->addJs('plugin://highlight/js/highlightjs-line-numbers.min.js', null, 'bottom');
		$this->grav['assets']->addCss('plugin://highlight/css/highlightjs-line-numbers.css', null, 'bottom');
	}
	$this->grav['assets']->addInlineJs($init, null, 'bottom');
}
```

But it seems to have made no difference so I guess that was naive. :)

**Comment by OleVik** [comment]
This should be easier with thew new `all_assets`-option in the main plugin.
